import {
  AcceptIcon,
  AccessibiltyCheckerIcon,
  AccountActivityIcon,
  AccountBrowserIcon,
  AccountManagementIcon,
  AccountsIcon,
  ActionCenterIcon,
  ActivateOrdersIcon,
  ActivityFeedIcon,
  AddBookmarkIcon,
  AddEventIcon,
  AddFavoriteIcon,
  AddFriendIcon,
  AddHomeIcon,
  AddIcon,
  AddInIcon,
  AddLinkIcon,
  AddNotesIcon,
  AddOnlineMeetingIcon,
  AddPhoneIcon,
  AddReactionIcon,
  AddSpaceAfterIcon,
  AlertSolidIcon,
  AnalyticsViewIcon,
  AnchorLockIcon,
  AutomateFlowIcon,
  BacklogIcon,
  BIDashboardIcon,
  BranchFork2Icon,
  BuildDefinitionIcon,
  BulletedTreeListIcon,
  BullseyeIcon,
  CalendarIcon,
  CarIcon,
  ClipboardListIcon,
  ClockIcon,
  CompanyDirectoryIcon,
  ConnectContactsIcon,
  ContactCardSettingsIcon,
  ContactInfoIcon,
  CRMReportIcon,
  CRMServicesIcon,
  DateTimeMirroredIcon,
  DeliveryTruckIcon,
  DeveloperToolsIcon,
  DiagnosticDataBarTooltipIcon,
  DiagnosticIcon,
  DOMIcon,
  FabricFolderIcon,
  FavoriteStarFillIcon,
  FeedbackIcon,
  FileSymlinkIcon,
  FinancialIcon,
  FlowChartIcon,
  FunctionalManagerDashboardIcon,
  GenericScanIcon,
  GroupIcon,
  HeadsetIcon,
  HealthIcon,
  HealthSolidIcon,
  ManufacturingIcon,
  MapDirectionsIcon,
  MobileReportIcon,
  MoneyIcon,
  OpenInNewWindowIcon,
  PageIcon,
  PostUpdateIcon,
  PowerBILogoIcon,
  ProductListIcon,
  ProjectCollectionIcon,
  PublishCourseIcon,
  ReceiptCheckIcon,
  ReopenPagesIcon,
  ReportDocumentIcon,
  RoomIcon,
  SaveIcon,
  SearchAndAppsIcon,
  SearchDataIcon,
  SunQuestionMarkIcon,
  SystemIcon,
  TableComputedIcon,
  TelemarketerIcon,
  ViewDashboardIcon,
  WebAppBuilderFragmentCreateIcon,
  WebAppBuilderFragmentIcon,
  WebsiteIcon,
  WindowEditIcon,
  WorkforceManagementIcon,
} from '@fluentui/react-icons';

export const fluentLibraryIcons = [
  { id: 'AcceptIcon', label: 'Accept', icon: AcceptIcon },
  {
    id: 'AccessibiltyCheckerIcon',
    label: 'Accessibilty Checker',
    icon: AccessibiltyCheckerIcon,
  },
  {
    id: 'AccountActivityIcon',
    label: 'Account Activity',
    icon: AccountActivityIcon,
  },
  {
    id: 'AccountBrowserIcon',
    label: 'Account Browser',
    icon: AccountBrowserIcon,
  },
  {
    id: 'AccountManagementIcon',
    label: 'Account Management',
    icon: AccountManagementIcon,
  },
  { id: 'AccountsIcon', label: 'Accounts', icon: AccountsIcon },
  { id: 'ActionCenterIcon', label: 'Action Center', icon: ActionCenterIcon },
  {
    id: 'ActivateOrdersIcon',
    label: 'Activate Orders',
    icon: ActivateOrdersIcon,
  },
  { id: 'ActivityFeedIcon', label: 'Activity Feed', icon: ActivityFeedIcon },
  { id: 'AddBookmarkIcon', label: 'Add Bookmark', icon: AddBookmarkIcon },
  { id: 'AddEventIcon', label: 'Add Event', icon: AddEventIcon },
  { id: 'AddFavoriteIcon', label: 'Add Favorite', icon: AddFavoriteIcon },
  { id: 'AddFriendIcon', label: 'Add Friend', icon: AddFriendIcon },
  { id: 'AddHomeIcon', label: 'Add Home', icon: AddHomeIcon },
  { id: 'AddIcon', label: 'Add', icon: AddIcon },
  { id: 'AddInIcon', label: 'Add In', icon: AddInIcon },
  { id: 'AddLinkIcon', label: 'Add Link', icon: AddLinkIcon },
  { id: 'AddNotesIcon', label: 'Add Notes', icon: AddNotesIcon },
  {
    id: 'AddOnlineMeetingIcon',
    label: 'Add Online Meeting',
    icon: AddOnlineMeetingIcon,
  },
  { id: 'AddPhoneIcon', label: 'Add Phone', icon: AddPhoneIcon },
  { id: 'AddReactionIcon', label: 'Add Reaction', icon: AddReactionIcon },
  {
    id: 'AddSpaceAfterIcon',
    label: 'Add Space After',
    icon: AddSpaceAfterIcon,
  },
  { id: 'AlertSolidIcon', label: 'Alert Solid', icon: AlertSolidIcon },
  { id: 'AnalyticsViewIcon', label: 'Analytics View', icon: AnalyticsViewIcon },
  { id: 'AnchorLockIcon', label: 'Anchor Lock', icon: AnchorLockIcon },
  { id: 'AutomateFlowIcon', label: 'Automate Flow', icon: AutomateFlowIcon },
  { id: 'BIDashboardIcon', label: 'BI Dashboard', icon: BIDashboardIcon },
  { id: 'BacklogIcon', label: 'Backlog', icon: BacklogIcon },
  { id: 'BranchFork2Icon', label: 'Branch Fork 2', icon: BranchFork2Icon },
  {
    id: 'BuildDefinitionIcon',
    label: 'Build Definition',
    icon: BuildDefinitionIcon,
  },
  {
    id: 'BulletedTreeListIcon',
    label: 'Bulleted Tree List',
    icon: BulletedTreeListIcon,
  },
  { id: 'BullseyeIcon', label: 'Bullseye', icon: BullseyeIcon },
  { id: 'CRMReportIcon', label: 'CRM Report', icon: CRMReportIcon },
  { id: 'CRMServicesIcon', label: 'CRM Services', icon: CRMServicesIcon },
  { id: 'CalendarIcon', label: 'Calendar', icon: CalendarIcon },
  { id: 'CarIcon', label: 'Car', icon: CarIcon },
  { id: 'ClipboardListIcon', label: 'Clipboard List', icon: ClipboardListIcon },
  { id: 'ClockIcon', label: 'Clock', icon: ClockIcon },
  {
    id: 'CompanyDirectoryIcon',
    label: 'Company Directory',
    icon: CompanyDirectoryIcon,
  },
  {
    id: 'ConnectContactsIcon',
    label: 'Connect Contacts',
    icon: ConnectContactsIcon,
  },
  {
    id: 'ContactCardSettingsIcon',
    label: 'Contact Card Settings',
    icon: ContactCardSettingsIcon,
  },
  { id: 'ContactInfoIcon', label: 'Contact Info', icon: ContactInfoIcon },
  { id: 'DOMIcon', label: 'DOM Icon', icon: DOMIcon },
  {
    id: 'DateTimeMirroredIcon',
    label: 'Date Time Mirrored',
    icon: DateTimeMirroredIcon,
  },
  { id: 'DeliveryTruckIcon', label: 'Delivery Truck', icon: DeliveryTruckIcon },
  {
    id: 'DeveloperToolsIcon',
    label: 'Developer Tools',
    icon: DeveloperToolsIcon,
  },
  {
    id: 'DiagnosticDataBarTooltipIcon',
    label: 'Diagnostic Data Bar Tooltip',
    icon: DiagnosticDataBarTooltipIcon,
  },
  { id: 'DiagnosticIcon', label: 'Diagnostic', icon: DiagnosticIcon },
  { id: 'FabricFolderIcon', label: 'Fabric Folder', icon: FabricFolderIcon },
  {
    id: 'FavoriteStarFillIcon',
    label: 'Favorite Star Fill',
    icon: FavoriteStarFillIcon,
  },
  { id: 'FeedbackIcon', label: 'Feedback', icon: FeedbackIcon },
  { id: 'FileSymlinkIcon', label: 'File Symlink', icon: FileSymlinkIcon },
  { id: 'FinancialIcon', label: 'Financial', icon: FinancialIcon },
  { id: 'FlowChartIcon', label: 'Flow Chart', icon: FlowChartIcon },
  {
    id: 'FunctionalManagerDashboardIcon',
    label: 'Functional Manager Dashboard',
    icon: FunctionalManagerDashboardIcon,
  },
  { id: 'GenericScanIcon', label: 'Generic Scan', icon: GenericScanIcon },
  { id: 'GroupIcon', label: 'Group', icon: GroupIcon },
  { id: 'HeadsetIcon', label: 'Headset', icon: HeadsetIcon },
  { id: 'HealthIcon', label: 'Health', icon: HealthIcon },
  { id: 'HealthSolidIcon', label: 'Health Solid', icon: HealthSolidIcon },
  { id: 'ManufacturingIcon', label: 'Manufacturing', icon: ManufacturingIcon },
  { id: 'MapDirectionsIcon', label: 'Map Directions', icon: MapDirectionsIcon },
  { id: 'MobileReportIcon', label: 'Mobile Report', icon: MobileReportIcon },
  { id: 'MoneyIcon', label: 'Money', icon: MoneyIcon },
  {
    id: 'OpenInNewWindowIcon',
    label: 'Open in New Window',
    icon: OpenInNewWindowIcon,
  },
  { id: 'PageIcon', label: 'Page', icon: PageIcon },
  { id: 'PostUpdateIcon', label: 'Post Update', icon: PostUpdateIcon },
  { id: 'PowerBILogoIcon', label: 'Power BI Logo', icon: PowerBILogoIcon },
  { id: 'ProductListIcon', label: 'Product List', icon: ProductListIcon },
  {
    id: 'ProjectCollectionIcon',
    label: 'Project Collection',
    icon: ProjectCollectionIcon,
  },
  { id: 'PublishCourseIcon', label: 'Publish Course', icon: PublishCourseIcon },
  { id: 'ReceiptCheckIcon', label: 'Receipt Check', icon: ReceiptCheckIcon },
  { id: 'ReopenPagesIcon', label: 'Reopen Pages', icon: ReopenPagesIcon },
  {
    id: 'ReportDocumentIcon',
    label: 'Report Document',
    icon: ReportDocumentIcon,
  },
  { id: 'RoomIcon', label: 'Room', icon: RoomIcon },
  { id: 'SaveIcon', label: 'Save', icon: SaveIcon },
  {
    id: 'SearchAndAppsIcon',
    label: 'Search And Apps',
    icon: SearchAndAppsIcon,
  },
  { id: 'SearchDataIcon', label: 'Search Data', icon: SearchDataIcon },
  {
    id: 'SunQuestionMarkIcon',
    label: 'Sun Question Mark',
    icon: SunQuestionMarkIcon,
  },
  { id: 'SystemIcon', label: 'System', icon: SystemIcon },
  { id: 'TableComputedIcon', label: 'Table Computed', icon: TableComputedIcon },
  { id: 'TelemarketerIcon', label: 'Telemarketer', icon: TelemarketerIcon },
  { id: 'ViewDashboardIcon', label: 'View Dashboard', icon: ViewDashboardIcon },
  {
    id: 'WebAppBuilderFragmentCreateIcon',
    label: 'Web App Builder Fragment Create',
    icon: WebAppBuilderFragmentCreateIcon,
  },
  {
    id: 'WebAppBuilderFragmentIcon',
    label: 'Web App Builder Fragment Icon',
    icon: WebAppBuilderFragmentIcon,
  },
  { id: 'WebsiteIcon', label: 'Website', icon: WebsiteIcon },
  { id: 'WindowEditIcon', label: 'Window Edit', icon: WindowEditIcon },
  {
    id: 'WorkforceManagementIcon',
    label: 'Workforce Management',
    icon: WorkforceManagementIcon,
  },
];
